import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { rullstSnippets } from "../data";
import { FileCode, Sparkles, Terminal, BookOpen, Layers, Eye, Check } from "lucide-react";

export default function SyntaxTour() {
  const [activeTab, setActiveTab] = useState<string>("template");
  const [compiledView, setCompiledView] = useState<"rust" | "wasm" | "html">("rust");
  const [copied, setCopied] = useState(false);

  const activeSnippet = rullstSnippets[activeTab];

  // Map simulated compilation structures for each snippet in English
  const compiledOutputs: Record<string, { rust: string; wasm: string; html: string }> = {
    template: {
      rust: `// Rullst compiles reactive Markdown layouts into native Rust structure
use rullst::html::{RawHtml, Component};

pub struct BlogHeader {
    pub post: Post,
}

impl Component for BlogHeader {
    fn render(&self) -> RawHtml {
        // Stack allocated strings rather than dynamic heap expansions for microseconds speed
        let mut html = String::with_capacity(512);
        html.push_str("<h1>Rullst Dev Blog</h1>");
        html.push_str("<p>Sleek full-stack Rust blog powered by Rullst & Active Record</p>");
        html.push_str(&format!("<h3>{}</h3>", self.post.title));
        html.push_str(&format!("<p>{}</p>", self.post.body));
        
        let posts_count = Post::all_sync_count(); // Uses dynamic transactional db queries
        html.push_str(&format!("<h1>Total System Posts: {}</h1>", posts_count));
        
        RawHtml::from(html)
    }
}`,
      wasm: `// WASM target module serving the client natively (total payload 34KB)
#[wasm_bindgen]
pub fn rullst_client_welcome_init() {
    let document = web_sys::window().unwrap().document().unwrap();
    let root = document.get_element_by_id("root").unwrap();
    
    // Binds events directly to the browser DOM without a Virtual DOM!
    let listener = Closure::wrap(Box::new(move |_e: Event| {
        // State updates execute inside the WebAssembly binary dynamically
        update_welcome_state();
    }) as Box<dyn FnMut(Event)>);
    
    root.add_event_listener_with_callback("click", &listener).unwrap();
    listener.forget();
}`,
      html: `<!-- Server-side rendered HTML response served in 120 microseconds -->
<div id="root">
  <h1>Rullst Dev Blog</h1>
  <p>Sleek full-stack Rust blog powered by Rullst & Active Record</p>
  <h3>Story of Tenant 1</h3>
  <p>This is exclusive content for tenant 1. Under Rullst SaaS Multi-tenancy...</p>
  <h1>Total System Posts: 2</h1>
</div>`,
    },
    orm: {
      rust: `// Highly optimized Rust database operations generated by #[rullst_orm::model]
impl Post {
    pub async fn save(&mut self) -> Result<(), sqlx::Error> {
        let pool = rullst_orm::Orm::pool()?;
        // Runs inline updates directly using ActiveRecord syntax
        if self.id == 0 {
            let row = sqlx::query!(
                "INSERT INTO posts (tenant_id, title, body) VALUES ($1, $2, $3) RETURNING id",
                self.tenant_id, self.title, self.body
            )
            .fetch_one(pool)
            .await?;
            self.id = row.id;
        } else {
            sqlx::query!(
                "UPDATE posts SET tenant_id = $1, title = $2, body = $3 WHERE id = $4",
                self.tenant_id, self.title, self.body, self.id
            )
            .execute(pool)
            .await?;
        }
        Ok(())
    }
}`,
      wasm: `// WASM runtime automatically maps query updates to browser caches
// avoiding complex REST AJAX frameworks or boilerplate serialization fetch layouts!
#[wasm_bindgen]
pub async fn sync_post_client(post_json: String) {
    let response = rullst_wasm_fetch("/api/posts/sync", post_json).await;
    update_local_browser_cache(response);
}`,
      html: `<!-- Implements database writes implicitly. High-performance active-record synchronization. -->
<!-- Backend pool processed operations via microsecond SQLite execution layers (0.05ms) -->`,
    },
    multitenant: {
      rust: `// Automates SQL transaction filters based on active worker threads
// Macro scoping wraps database transactions securing thread-local multi-tenancies
tokio::task_local! {
    pub static ACTIVE_TENANT: RefCell<Option<String>>;
}

impl Post {
    pub async fn all() -> Result<Vec<Post>, sqlx::Error> {
        let pool = rullst_orm::Orm::pool()?;
        // Rullst implicitly reads current active tenant constraints from asynchronous task states!
        let tenant_id = multitenant::get_current_tenant();
        
        let posts = sqlx::query_as!(
            Post,
            "SELECT * FROM posts WHERE tenant_id = $1",
            tenant_id
        )
        .fetch_all(pool)
        .await?;
        
        Ok(posts)
    }
}`,
      wasm: `// Cryptographically derived tenant tokens map natively 
// into request hooks, preventing client-side spoofing
let tenant_token = get_secured_cookie("x-tenant-context");
set_wasm_header("x-tenant-id", tenant_token);`,
      html: `<!-- Scoped database answers isolated for appropriate tenants -->
<div class="tenant-isolated-card" data-tenant="tenant1">
  <!-- Only Stark Industries models are visible dynamically -->
  <h3>Clean Energy Breakthrough</h3>
</div>`,
    },
    hotreload: {
      rust: `// Dynamically swaps active shared library logic (.dylib / .so)
// PRIMARY router dynamically rebinds routes without restarting socket loops
pub struct HotServer {
    lib: libloading::Library,
}

impl HotServer {
    pub fn reload(&mut self, path: &str) {
        unsafe {
            // Safely cleans previous routing structures in memory
            self.lib.close().unwrap();
            
            // Hot swaps fresh compiled path routes in microseconds
            self.lib = libloading::Library::new(path).unwrap();
            let init_router: Symbol<fn() -> *mut Router> = self.lib.get(b"rullst_router_init").unwrap();
            self.update_router(init_router());
        }
    }
}`,
      wasm: `// WASM Hot Reloading: Rullst binds a low-level WebSocket connection
// to trigger immediate updates under client runtimes without full page reloads!`,
      html: `<!-- Fresh layout compiles immediately upon shared library swap -->`,
    },
    artisan: {
      rust: `// Seamless background helper CLI mapping artisan macro structures
#[macro_export]
macro_rules! artisan {
    ($args:expr) => {
        let parsed = rullst::cli::parse_artisan_arguments($args);
        if parsed.is_command() {
            rullst::cli::execute_command(parsed).await;
            std::process::exit(0); // Gracefully terminates CLI context
        }
    }
}`,
      wasm: `// Excludes developmental commands inside production bundlers,
// keeping payloads under 34KB focusing 100% on delivery.`,
      html: `<!-- Developer CLI commands do not alter client production HTML structures. -->`,
    },
  };

  const copyCode = () => {
    navigator.clipboard.writeText(activeSnippet.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="py-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      {/* Grid Content Showcase info */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-start">
        {/* Left Side: Information and Navigation */}
        <div className="lg:col-span-5 flex flex-col space-y-6">
          <div>
            <span className="flex items-center space-x-1.5 px-3 py-1 bg-cyan-500/10 border border-cyan-500/20 rounded-full text-xs font-mono font-medium text-cyan-400 w-fit">
              <Sparkles className="w-3.5 h-3.5 animate-pulse" />
              <span>MARKDOWN-FIRST COMPILER</span>
            </span>
            <h2 className="text-3xl sm:text-4xl font-display font-extrabold text-white mt-4">
              Syntax & Compiler Explorer
            </h2>
            <p className="text-gray-400 text-sm mt-3 leading-relaxed">
              Rullst bypasses bloated structural HTML or tedious XML tags. Our custom procedural macros analyze markdown and dynamic reactive signals directly, compiling them into blazing-fast native target instructions.
            </p>
          </div>

          {/* Feature List buttons to show */}
          <div className="flex flex-col space-y-2.5">
            {[
              { id: "template", label: "Markdown Templating DSL", desc: "Sleek markdown components with dynamic reactive inputs." },
              { id: "orm", label: "ORM ActiveRecord", desc: "Eloquent ActiveRecord simplicity mapped directly to type-safe Rust structures." },
              { id: "multitenancy", label: "Tenants Isolation", desc: "Thread-scoped database boundaries protected naturally from data leaks." },
              { id: "hotreload", label: "Binary Hot Reload", desc: "Compile and observe system layouts dynamically in milliseconds." },
              { id: "artisan", label: "Artisan & Studio CLI", desc: "Maximize development loops using modern unified CLI scaffolding." },
            ].map((item) => (
              <button
                key={item.id}
                onClick={() => {
                  setActiveTab(item.id);
                  setCompiledView("rust");
                }}
                className={`flex flex-col text-left p-4 rounded-xl border transition-all duration-200 ${
                  activeTab === item.id
                    ? "bg-gradient-to-r from-gray-900 to-gray-800 border-orange-500/30 shadow shadow-orange-500/5"
                    : "bg-gray-900/20 border-gray-800 hover:bg-gray-900/50 hover:border-gray-700"
                }`}
              >
                <span className={`text-sm font-semibold ${activeTab === item.id ? "text-orange-400" : "text-gray-200"}`}>
                  {item.label}
                </span>
                <span className="text-xs text-gray-400 mt-1">{item.desc}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Right Side: Double Editor View Code vs Compilator */}
        <div className="lg:col-span-7 flex flex-col space-y-6">
          {/* Editor 1: Input Code */}
          <div className="rounded-xl border border-gray-800 bg-[#060a12]/90 shadow-2xl overflow-hidden">
            <div className="flex items-center justify-between px-4 py-2.5 bg-gray-900/60 border-b border-gray-800">
              <div className="flex items-center space-x-2">
                <FileCode className="w-4 h-4 text-orange-400" />
                <span className="text-xs font-mono text-gray-300">
                  {activeTab === "artisan" ? "shell_command" : "src/components/" + activeTab + ".rs"}
                </span>
              </div>
              <button
                onClick={copyCode}
                className="flex items-center space-x-1.5 px-2.5 py-1 text-[10px] sm:text-xs font-mono text-gray-400 hover:text-white bg-gray-800/40 hover:bg-gray-800 rounded transition-colors"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Eye className="w-3.5 h-3.5" />}
                <span>{copied ? "Copied!" : "Copy"}</span>
              </button>
            </div>
            <div className="p-4 sm:p-5 overflow-x-auto font-mono text-xs sm:text-sm text-gray-300 leading-relaxed max-h-[290px] overflow-y-auto">
              <pre>{activeSnippet.code}</pre>
            </div>
            <div className="bg-gray-900/40 px-4 py-3 border-t border-gray-800 flex items-start gap-2.5 text-xs text-gray-400 leading-relaxed">
              <BookOpen className="w-4 h-4 text-orange-500 shrink-0 mt-0.5" />
              <span>{activeSnippet.explanation}</span>
            </div>
          </div>

          {/* Editor 2: Compiler Output expanded */}
          <div className="rounded-xl border border-gray-800 bg-[#02050a]/90 shadow-2xl overflow-hidden">
            <div className="flex items-center justify-between px-4 py-2.5 bg-gray-900/80 border-b border-gray-800">
              <span className="text-xs font-mono text-cyan-400 flex items-center">
                <Terminal className="w-4 h-4 mr-1.5 text-cyan-400" />
                RULLST COMPILER OUTPUT
              </span>

              {/* Toggles compiled view */}
              <div className="flex space-x-1 bg-gray-950 p-0.5 rounded border border-gray-800">
                <button
                  onClick={() => setCompiledView("rust")}
                  className={`px-2.5 py-1 text-[10px] font-mono rounded ${
                    compiledView === "rust" ? "bg-gray-800 text-white font-bold" : "text-gray-400 hover:text-white"
                  }`}
                >
                  Recompiled Rust
                </button>
                <button
                  onClick={() => setCompiledView("wasm")}
                  className={`px-2.5 py-1 text-[10px] font-mono rounded ${
                    compiledView === "wasm" ? "bg-gray-800 text-white font-bold" : "text-gray-400 hover:text-white"
                  }`}
                >
                  Client WASM
                </button>
                <button
                  onClick={() => setCompiledView("html")}
                  className={`px-2.5 py-1 text-[10px] font-mono rounded ${
                    compiledView === "html" ? "bg-gray-800 text-white font-bold" : "text-gray-400 hover:text-white"
                  }`}
                >
                  HTML SSR (0.12ms)
                </button>
              </div>
            </div>

            <div className="p-4 sm:p-5 overflow-x-auto font-mono text-xs text-gray-400 leading-relaxed max-h-[290px] overflow-y-auto">
              <AnimatePresence mode="wait">
                <motion.pre
                  key={compiledView}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.15 }}
                >
                  {compiledOutputs[activeTab]?.[compiledView] || "// No dynamic outputs compiled for this format."}
                </motion.pre>
              </AnimatePresence>
            </div>
            <div className="bg-gray-900/20 px-4 py-3 border-t border-gray-800 flex items-center justify-between text-[10px] text-gray-400 font-mono">
              <span className="flex items-center gap-1">
                <Layers className="w-3.5 h-3.5 text-cyan-400" /> OPTIMIZATION FLAGS: MAX_INLINE
              </span>
              <span>COMPILED IN <strong className="text-cyan-400">0.02ms</strong></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
